### ISSUE TITLE
Sync after following user

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/subconscious#555] opened 2023-04-25 22:05 UTC
You won't get the did immediately, since it will take some time for the name to resolve. Use exponential backoff.

> @cdata: Doing it a couple times over 2-3 seconds will mostly get you the new sphere right away.

**Comment by gordonbrander** [comment] 2023-05-09 21:34
Playtesting 2023-05-09: it seems that we aren't syncing after following.

**Comment by bfollington** [comment] 2023-05-10 04:34
We should sync _and_ repeatedly check for resolution of the DID after adding a user. 

We should display an indication in the UI if a user has not yet resolved and prevent tapping on them.

**Comment by bfollington** [comment] 2023-05-10 21:50
Duplicate of https://github.com/subconsciousnetwork/subconscious/issues/492

**Closed** 2023-05-22 00:11 UTC
Labels: Enhancement
