### ISSUE TITLE
Notes disppeared after updating Subconscious to `aa68b88`

### ISSUE THREAD

**Issue by cdata** [subconsciousnetwork/subconscious#733] opened 2023-06-19 15:41 UTC
I ran into a potential esoteric problem where, after updating my existing Subconscious installations to the latest as of https://github.com/subconsciousnetwork/subconscious/commit/aa68b885055e1f03b15a37c0021da3ad78118971, my notes seemingly disappeared from the notes list. After adding a new note, the notes reappeared. Attached are the logs from the first run after the update, as well as a video of the problem.

https://github.com/subconsciousnetwork/subconscious/assets/240083/224ad4e3-18b1-4ddc-aff0-b5473517ded1

```
2023-06-19 08:32:17.259938-0700 Subconscious[1751:47338039] [NoosphereService] msg="init NoosphereService" globalStorageURL="file:///Users/cdata/Library/Developer/CoreSimulator/Devices/69B8DC73-FF70-4B58-907C-277C31E46396/data/Containers/Data/Application/CD6897A7-7355-4E9A-A202-A820425E00F6/Library/Application%20Support/noosphere" sphereStorageURL="file:///Users/cdata/Library/Developer/CoreSimulator/Devices/69B8DC73-FF70-4B58-907C-277C31E46396/data/Containers/Data/Application/CD6897A7-7355-4E9A-A202-A820425E00F6/Library/Application%20Support/sphere" gatewayURL="https://bdyqprful3tazye7uwrlcsjs2ttqelq3.sphere.test.subconscious.cloud/" sphereIdentity="did:key:z6MkqWcTm7VxZbRAWEvBY8MajNaoVw8uuWfuS2hpjo4H9k6w"
2023-06-19 08:32:17.264914-0700 Subconscious[1751:47338039] [app] Set sphere ID: did:key:z6MkqWcTm7VxZbRAWEvBY8MajNaoVw8uuWfuS2hpjo4H9k6w
2023-06-19 08:32:17.373433-0700 Subconscious[1751:47338039] [app] msg="appear" documents="file:///Users/cdata/Library/Developer/CoreSimulator/Devices/69B8DC73-FF70-4B58-907C-277C31E46396/data/Containers/Data/Application/CD6897A7-7355-4E9A-A202-A820425E00F6/Documents/" database="file:///Users/cdata/Library/Developer/CoreSimulator/Devices/69B8DC73-FF70-4B58-907C-277C31E46396/data/Containers/Data/Application/CD6897A7-7355-4E9A-A202-A820425E00F6/Library/Application%20Support/database.sqlite" sphereIdentity="did:key:z6MkqWcTm7VxZbRAWEvBY8MajNaoVw8uuWfuS2hpjo4H9k6w" isNoosphereEnabled="true"
2023-06-19 08:32:17.373849-0700 Subconscious[1751:47338039] [app] Readying database
2023-06-19 08:32:17.376942-0700 Subconscious[1751:47338039] [app] [action] appear
2023-06-19 08:32:17.377578-0700 Subconscious[1751:47338039] [notebook] [action] appear
2023-06-19 08:32:17.383374-0700 Subconsc2023-06-19 08:32:17.411234-0700 Subconscious[1751:47338039] Metal GPU Frame Capture Enabled
ious[1751:47338467] [NoosphereService] init Noosphere
2023-06-19 08:32:17.460827-0700 Subconscious[1751:47338039] Metal API Validation Enabled
2023-06-19 08:32:17.490693-0700 Subconscious[1751:47338467] [Noosphere] init
2023-06-19 08:32:17.490886-0700 Subconscious[1751:47338467] [NoosphereService] init Sphere with identity: did:key:z6MkqWcTm7VxZbRAWEvBY8MajNaoVw8uuWfuS2hpjo4H9k6w
2023-06-19 08:32:17.509533-0700 Subconscious[1751:47338467] [Sphere] init with identity: did:key:z6MkqWcTm7VxZbRAWEvBY8MajNaoVw8uuWfuS2hpjo4H9k6w
Reading sphere did:key:z6MkrdX8pUfnGef3zwzDo5etdiz57pvdT9T2bmiM4UGwVPka slug _profile_...
Reading sphere did:key:z6Mko6McViVcsDSBkaZmn39tvqPQpvR66S8H6aGmLghREqh3 slug _profile_...
Reading sphere did:key:z6MktdGJAekLdBE7X7t4wUv9tAqVeq1pYuNzDYHkEWtbiMKj slug _profile_...
Reading sphere did:key:z6MkoKiwk5zzNn8Ugo3BeXqa5mapC6S8aJdd953WY4ArVHe6 slug _profile_...
2023-06-19 08:32:17.519839-0700 Subconscious[1751:47338466] [UserProfileService] Failed to read profile at @subconscious/_profile_: Foreign Error: No version has been resolved for "subconscious" (did:key:z6MkmCJAZansQ3p1Qwx6wrF4c64yt2rcM8wMrH5Rh7DGb2K7)
Reading sphere did:key:z6MkqWcTm7VxZbRAWEvBY8MajNaoVw8uuWfuS2hpjo4H9k6w slug some-thoughts...
Reading sphere did:key:z6MkqWcTm7VxZbRAWEvBY8MajNaoVw8uuWfuS2hpjo4H9k6w slug who-am-ai...
Reading sphere did:key:z6MkqWcTm7VxZbRAWEvBY8MajNaoVw8uuWfuS2hpjo4H9k6w slug _profile_...
2023-06-19 08:32:17.601937-0700 Subconscious[1751:47338039] [app] [action] notifyNoosphereEnabled(true)
2023-06-19 08:32:17.602240-0700 Subconscious[1751:47338039] [app] [action] rebuildDatabase
2023-06-19 08:32:17.602380-0700 Subconscious[1751:47338039] [app] No valid migrations for database. Rebuilding.
2023-06-19 08:32:17.603172-0700 Subconscious[1751:47338039] [app] [action] succeedRefreshSphereVersion("bafyr4ibkxqkkld7zaqbdegtkvliane2or6j5njmhcloaon2jms464vs2km")
2023-06-19 08:32:17.603221-0700 Subconscious[1751:47338039] [app] Refreshed sphere version: bafyr4ibkxqkkld7zaqbdegtkvliane2or6j5njmhcloaon2jms464vs2km
2023-06-19 08:32:17.625300-0700 Subconscious[1751:47338039] [app] [action] succeedFetchNicknameFromProfile(cdata-sim)
2023-06-19 08:32:17.625814-0700 Subconscious[1751:47338039] [app] Nickname saved: cdata-sim
Reading sphere did:key:z6MkqWcTm7VxZbRAWEvBY8MajNaoVw8uuWfuS2hpjo4H9k6w slug _profile_...
2023-06-19 08:32:17.626857-0700 Subconscious[1751:47338039] [app] [action] succeedRebuildDatabase(1686760140)
2023-06-19 08:32:17.626951-0700 Subconscious[1751:47338039] [app] Rebuilt database
2023-06-19 08:32:17.627015-0700 Subconscious[1751:47338039] [app] Database version: 1686760140
2023-06-19 08:32:17.627574-0700 Subconscious[1751:47338039] [app] msg="Last index for our sphere" identity="nil" version="nil"
2023-06-19 08:32:17.627930-0700 Subconscious[1751:47338039] [app] msg="Syncing with gateway" url="https://bdyqprful3tazye7uwrlcsjs2ttqelq3.sphere.test.subconscious.cloud/"
2023-06-19 08:32:17.628149-0700 Subconscious[1751:47338039] [app] File sync started
Writing sphere did:key:z6MkqWcTm7VxZbRAWEvBY8MajNaoVw8uuWfuS2hpjo4H9k6w slug _profile_...
Updated "_profile_"...
Saved sphere; new revision is bafyr4ifcysyl5cwt2ar626s3lqwz6y4t43ue3yke3af7sg75emta4fz5hu
2023-06-19 08:32:17.644177-0700 Subconscious[1751:47338039] [notebook] [action] ready
2023-06-19 08:32:17.644242-0700 Subconscious[1751:47338039] [app] [action] succeedSyncLocalFilesWithDatabase(...) 0 items
2023-06-19 08:32:17.644285-0700 Subconscious[1751:47338039] [app] File sync finished: []
Update NavigationAuthority bound path tried to update multiple times per frame.
2023-06-19 08:32:17.651102-0700 Subconscious[1751:47338039] [app] [action] scenePhaseChange(SwiftUI.ScenePhase.active)
2023-06-19 08:32:17.710763-0700 Subconscious[1751:47338039] [notebook] [action] search(setSuggestions(2 items))
2023-06-19 08:32:17.710980-0700 Subconscious[1751:47338039] [notebook] [action] setEntryCount(0)
2023-06-19 08:32:17.711035-0700 Subconscious[1751:47338039] [notebook] [action] setRecent(0 items)
Syncing received local sphere revisions...
Considering 3 updated link records for adoption...
Syncing received local sphere revisions...
Considering 3 updated link records for adoption...
Collecting blocks from new local history...
2023-06-19 08:32:20.894800-0700 Subconscious[1751:47338039] [app] [action] failSyncSphereWithGateway("Foreign Error: No changes to save")
2023-06-19 08:32:20.894942-0700 Subconscious[1751:47338039] [app] msg="Sphere failed to sync with gateway" error="Foreign Error: No changes to save"
 WARN Unrecognized content type "application/vnd.subconscious.profile+json"; attempting to bundle as body chunks...
 WARN Unrecognized content type "application/vnd.subconscious.profile+json"; attempting to bundle as body chunks...
Pushing new local history to gateway did:key:z6MkutMYQ2SnZ8MAU4La8Qva4evL8DkAgjnfx5tHMbeKuzJf...
2023-06-19 08:32:20.896349-0700 Subconscious[1751:47338463] [DataService] msg="Created record for peer" petname="benny" identity="did:key:z6MkrdX8pUfnGef3zwzDo5etdiz57pvdT9T2bmiM4UGwVPka" since="nil"
2023-06-19 08:32:20.896476-0700 Subconscious[1751:47338463] [DataService] msg="Created record for peer" petname="cdata" identity="did:key:z6Mko6McViVcsDSBkaZmn39tvqPQpvR66S8H6aGmLghREqh3" since="nil"
2023-06-19 08:32:20.896620-0700 Subconscious[1751:47338463] [DataService] msg="Created record for peer" petname="gorgor" identity="did:key:z6MktdGJAekLdBE7X7t4wUv9tAqVeq1pYuNzDYHkEWtbiMKj" since="nil"
2023-06-19 08:32:20.896718-0700 Subconscious[1751:47338463] [DataService] msg="Created record for peer" petname="j" identity="did:key:z6MkoKiwk5zzNn8Ugo3BeXqa5mapC6S8aJdd953WY4ArVHe6" since="nil"
2023-06-19 08:32:20.896846-0700 Subconscious[1751:47338463] [DataService] msg="Created record for peer" petname="subconscious" identity="did:key:z6MkmCJAZansQ3p1Qwx6wrF4c64yt2rcM8wMrH5Rh7DGb2K7" since="nil"
Reading sphere did:key:z6MkqWcTm7VxZbRAWEvBY8MajNaoVw8uuWfuS2hpjo4H9k6w slug _profile_...
Reading sphere did:key:z6MkqWcTm7VxZbRAWEvBY8MajNaoVw8uuWfuS2hpjo4H9k6w slug some-thoughts...
Reading sphere did:key:z6MkqWcTm7VxZbRAWEvBY8MajNaoVw8uuWfuS2hpjo4H9k6w slug who-am-ai...
2023-06-19 08:32:20.901269-0700 Subconscious[1751:47338463] [DataService] msg="Indexed our sphere" identity="did:key:z6MkqWcTm7VxZbRAWEvBY8MajNaoVw8uuWfuS2hpjo4H9k6w" version="bafyr4idhnx4deslhqtoxcqns7vzx5obdgshwbzisbcu2o4e5r2aksqbkvu"
2023-06-19 08:32:20.902339-0700 Subconscious[1751:47338039] [app] [action] succeedIndexOurSphere(Subconscious.OurSphereRecord(identity: did:key:z6MkqWcTm7VxZbRAWEvBY8MajNaoVw8uuWfuS2hpjo4H9k6w, since: "bafyr4idhnx4deslhqtoxcqns7vzx5obdgshwbzisbcu2o4e5r2aksqbkvu"))
2023-06-19 08:32:20.902497-0700 Subconscious[1751:47338039] [app] msg="Indexed our sphere" identity="did:key:z6MkqWcTm7VxZbRAWEvBY8MajNaoVw8uuWfuS2hpjo4H9k6w" version="bafyr4idhnx4deslhqtoxcqns7vzx5obdgshwbzisbcu2o4e5r2aksqbkvu"
2023-06-19 08:32:20.902852-0700 Subconscious[1751:47338039] [app] msg="Collecting peers to index"
2023-06-19 08:32:20.909118-0700 Subconscious[1751:47338039] [app] [action] succeedCollectPeersToIndex([Subconscious.PeerRecord(petname: benny, identity: did:key:z6MkrdX8pUfnGef3zwzDo5etdiz57pvdT9T2bmiM4UGwVPka, since: nil), Subconscious.PeerRecord(petname: cdata, identity: did:key:z6Mko6McViVcsDSBkaZmn39tvqPQpvR66S8H6aGmLghREqh3, since: nil), Subconscious.PeerRecord(petname: gorgor, identity: did:key:z6MktdGJAekLdBE7X7t4wUv9tAqVeq1pYuNzDYHkEWtbiMKj, since: nil), Subconscious.PeerRecord(petname: j, identity: did:key:z6MkoKiwk5zzNn8Ugo3BeXqa5mapC6S8aJdd953WY4ArVHe6, since: nil), Subconscious.PeerRecord(petname: subconscious, identity: did:key:z6MkmCJAZansQ3p1Qwx6wrF4c64yt2rcM8wMrH5Rh7DGb2K7, since: nil)])
2023-06-19 08:32:20.909449-0700 Subconscious[1751:47338039] [app] [action] indexPeer(benny)
2023-06-19 08:32:20.909710-0700 Subconscious[1751:47338039] [app] msg="Indexing peer" petname="benny"
2023-06-19 08:32:20.909840-0700 Subconscious[1751:47338039] [app] [action] indexPeer(cdata)
2023-06-19 08:32:20.909893-0700 Subconscious[1751:47338039] [app] msg="Indexing peer" petname="cdata"
2023-06-19 08:32:20.909985-0700 Subconscious[1751:47338039] [app] [action] indexPeer(gorgor)
2023-06-19 08:32:20.910029-0700 Subconscious[1751:47338039] [app] msg="Indexing peer" petname="gorgor"
2023-06-19 08:32:20.910106-0700 Subconscious[1751:47338039] [app] [action] indexPeer(j)
2023-06-19 08:32:20.910149-0700 Subconscious[1751:47338039] [app] msg="Indexing peer" petname="j"
2023-06-19 08:32:20.910259-0700 Subconscious[1751:47338039] [app] [action] indexPeer(subconscious)
2023-06-19 08:32:20.910298-0700 Subconscious[1751:47338039] [app] msg="Indexing peer" petname="subconscious"
2023-06-19 08:32:20.911024-0700 Subconscious[1751:47338482] [Sphere] init from pointer with identity: did:key:z6MktdGJAekLdBE7X7t4wUv9tAqVeq1pYuNzDYHkEWtbiMKj
2023-06-19 08:32:20.911105-0700 Subconscious[1751:47338482] [Sphere] init from pointer with identity: did:key:z6MkoKiwk5zzNn8Ugo3BeXqa5mapC6S8aJdd953WY4ArVHe6
2023-06-19 08:32:20.911207-0700 Subconscious[1751:47338454] [DataService] msg="Traversed to peer" petname="gorgor"
2023-06-19 08:32:20.912119-0700 Subconscious[1751:47338454] [DataService] msg="Traversed to peer" petname="j"
2023-06-19 08:32:20.913042-0700 Subconscious[1751:47338039] [app] [action] failIndexPeer(petname: subconscious, error: Subconscious.NoosphereError.foreignError("No version has been resolved for \"subconscious\" (did:key:z6MkmCJAZansQ3p1Qwx6wrF4c64yt2rcM8wMrH5Rh7DGb2K7)"))
2023-06-19 08:32:20.913190-0700 Subconscious[1751:47338039] [app] msg="Failed to index peer" petname="subconscious" error="Foreign Error: No version has been resolved for \"subconscious\" (did:key:z6MkmCJAZansQ3p1Qwx6wrF4c64yt2rcM8wMrH5Rh7DGb2K7)"
2023-06-19 08:32:20.914095-0700 Subconscious[1751:47338466] [DataService] msg="Indexing peer" petname="j" identity="did:key:z6MkoKiwk5zzNn8Ugo3BeXqa5mapC6S8aJdd953WY4ArVHe6" version="bafyr4iaichqv2akoe5pjtzxqsqey6cxrqnxap45zv7kshp24bhyp36gmie" since="nil" changes="1"
Reading sphere did:key:z6MkoKiwk5zzNn8Ugo3BeXqa5mapC6S8aJdd953WY4ArVHe6 slug _profile_...
2023-06-19 08:32:20.916815-0700 Subconscious[1751:47338466] [DataService] msg="Indexed memo /_profile_" slashlink="/_profile_"
2023-06-19 08:32:20.918896-0700 Subconscious[1751:47338466] [DataService] msg="Indexed peer" petname="j" identity="did:key:z6MkoKiwk5zzNn8Ugo3BeXqa5mapC6S8aJdd953WY4ArVHe6" version="bafyr4iaichqv2akoe5pjtzxqsqey6cxrqnxap45zv7kshp24bhyp36gmie" since="nil"
2023-06-19 08:32:20.919116-0700 Subconscious[1751:47338466] [Sphere] deinit with identity did:key:z6MkoKiwk5zzNn8Ugo3BeXqa5mapC6S8aJdd953WY4ArVHe6
2023-06-19 08:32:20.919638-0700 Subconscious[1751:47338039] [app] [action] succeedIndexPeer(Subconscious.PeerRecord(petname: j, identity: did:key:z6MkoKiwk5zzNn8Ugo3BeXqa5mapC6S8aJdd953WY4ArVHe6, since: Optional("bafyr4iaichqv2akoe5pjtzxqsqey6cxrqnxap45zv7kshp24bhyp36gmie")))
2023-06-19 08:32:20.919698-0700 Subconscious[1751:47338039] [app] msg="Indexed peer" petname="j" identity="did:key:z6MkoKiwk5zzNn8Ugo3BeXqa5mapC6S8aJdd953WY4ArVHe6" since="bafyr4iaichqv2akoe5pjtzxqsqey6cxrqnxap45zv7kshp24bhyp36gmie"
Saving updated counterpart sphere history...
2023-06-19 08:32:21.067922-0700 Subconscious[1751:47338039] [app] [action] succeedCreateUpdateNickname
2023-06-19 08:32:21.068020-0700 Subconscious[1751:47338039] [app] Wrote initial profile memo
2023-06-19 08:32:21.389480-0700 Subconscious[1751:47338454] [DataService] msg="Indexing peer" petname="gorgor" identity="did:key:z6MktdGJAekLdBE7X7t4wUv9tAqVeq1pYuNzDYHkEWtbiMKj" version="bafyr4ifddrjh5rgppz324zb6a6ny3ejlbx53c3xh44aq2clcxcbfdlvq44" since="nil" changes="3"
Reading sphere did:key:z6MktdGJAekLdBE7X7t4wUv9tAqVeq1pYuNzDYHkEWtbiMKj slug _profile_...
2023-06-19 08:32:21.391707-0700 Subconscious[1751:47338454] [DataService] msg="Indexed memo /_profile_" slashlink="/_profile_"
Reading sphere did:key:z6MktdGJAekLdBE7X7t4wUv9tAqVeq1pYuNzDYHkEWtbiMKj slug foo...
2023-06-19 08:32:21.394004-0700 Subconscious[1751:47338454] [DataService] msg="Indexed memo /foo" slashlink="/foo"
Reading sphere did:key:z6MktdGJAekLdBE7X7t4wUv9tAqVeq1pYuNzDYHkEWtbiMKj slug test...
2023-06-19 08:32:21.395486-0700 Subconscious[1751:47338454] [DataService] msg="Indexed memo /test" slashlink="/test"
2023-06-19 08:32:21.396960-0700 Subconscious[1751:47338454] [DataService] msg="Indexed peer" petname="gorgor" identity="did:key:z6MktdGJAekLdBE7X7t4wUv9tAqVeq1pYuNzDYHkEWtbiMKj" version="bafyr4ifddrjh5rgppz324zb6a6ny3ejlbx53c3xh44aq2clcxcbfdlvq44" since="nil"
2023-06-19 08:32:21.397257-0700 Subconscious[1751:47338454] [Sphere] deinit with identity did:key:z6MktdGJAekLdBE7X7t4wUv9tAqVeq1pYuNzDYHkEWtbiMKj
2023-06-19 08:32:21.397642-0700 Subconscious[1751:47338039] [app] [action] succeedIndexPeer(Subconscious.PeerRecord(petname: gorgor, identity: did:key:z6MktdGJAekLdBE7X7t4wUv9tAqVeq1pYuNzDYHkEWtbiMKj, since: Optional("bafyr4ifddrjh5rgppz324zb6a6ny3ejlbx53c3xh44aq2clcxcbfdlvq44")))
2023-06-19 08:32:21.397742-0700 Subconscious[1751:47338039] [app] msg="Indexed peer" petname="gorgor" identity="did:key:z6MktdGJAekLdBE7X7t4wUv9tAqVeq1pYuNzDYHkEWtbiMKj" since="bafyr4ifddrjh5rgppz324zb6a6ny3ejlbx53c3xh44aq2clcxcbfdlvq44"
2023-06-19 08:32:21.704991-0700 Subconscious[1751:47338535] [Sphere] init from pointer with identity: did:key:z6MkrdX8pUfnGef3zwzDo5etdiz57pvdT9T2bmiM4UGwVPka
2023-06-19 08:32:21.705274-0700 Subconscious[1751:47338454] [DataService] msg="Traversed to peer" petname="benny"
2023-06-19 08:32:21.898954-0700 Subconscious[1751:47338536] [Sphere] init from pointer with identity: did:key:z6Mko6McViVcsDSBkaZmn39tvqPQpvR66S8H6aGmLghREqh3
2023-06-19 08:32:21.899260-0700 Subconscious[1751:47338466] [DataService] msg="Traversed to peer" petname="cdata"
2023-06-19 08:32:22.158008-0700 Subconscious[1751:47338454] [DataService] msg="Indexing peer" petname="benny" identity="did:key:z6MkrdX8pUfnGef3zwzDo5etdiz57pvdT9T2bmiM4UGwVPka" version="bafyr4ihkb3vcyou2ma7zn745c3ztrpfgacipacnlzoey5dl5jqxinp2zkq" since="nil" changes="3"
Reading sphere did:key:z6MkrdX8pUfnGef3zwzDo5etdiz57pvdT9T2bmiM4UGwVPka slug _profile_...
2023-06-19 08:32:22.161644-0700 Subconscious[1751:47338464] [DataService] msg="Indexed memo /_profile_" slashlink="/_profile_"
Reading sphere did:key:z6MkrdX8pUfnGef3zwzDo5etdiz57pvdT9T2bmiM4UGwVPka slug _profile_-2...
2023-06-19 08:32:22.163973-0700 Subconscious[1751:47338464] [DataService] msg="Indexed memo /_profile_-2" slashlink="/_profile_-2"
Reading sphere did:key:z6MkrdX8pUfnGef3zwzDo5etdiz57pvdT9T2bmiM4UGwVPka slug babys-first-note...
2023-06-19 08:32:22.166680-0700 Subconscious[1751:47338464] [DataService] msg="Indexed memo /babys-first-note" slashlink="/babys-first-note"
2023-06-19 08:32:22.168144-0700 Subconscious[1751:47338464] [DataService] msg="Indexed peer" petname="benny" identity="did:key:z6MkrdX8pUfnGef3zwzDo5etdiz57pvdT9T2bmiM4UGwVPka" version="bafyr4ihkb3vcyou2ma7zn745c3ztrpfgacipacnlzoey5dl5jqxinp2zkq" since="nil"
2023-06-19 08:32:22.168845-0700 Subconscious[1751:47338464] [Sphere] deinit with identity did:key:z6MkrdX8pUfnGef3zwzDo5etdiz57pvdT9T2bmiM4UGwVPka
2023-06-19 08:32:22.169133-0700 Subconscious[1751:47338039] [app] [action] succeedIndexPeer(Subconscious.PeerRecord(petname: benny, identity: did:key:z6MkrdX8pUfnGef3zwzDo5etdiz57pvdT9T2bmiM4UGwVPka, since: Optional("bafyr4ihkb3vcyou2ma7zn745c3ztrpfgacipacnlzoey5dl5jqxinp2zkq")))
2023-06-19 08:32:22.169299-0700 Subconscious[1751:47338039] [app] msg="Indexed peer" petname="benny" identity="did:key:z6MkrdX8pUfnGef3zwzDo5etdiz57pvdT9T2bmiM4UGwVPka" since="bafyr4ihkb3vcyou2ma7zn745c3ztrpfgacipacnlzoey5dl5jqxinp2zkq"
2023-06-19 08:32:22.402439-0700 Subconscious[1751:47338466] [DataService] msg="Indexing peer" petname="cdata" identity="did:key:z6Mko6McViVcsDSBkaZmn39tvqPQpvR66S8H6aGmLghREqh3" version="bafyr4ifyqruqswigidlxxxma25o4nv4jc2depin4padtqvej6intmetxbi" since="nil" changes="12"
Reading sphere did:key:z6Mko6McViVcsDSBkaZmn39tvqPQpvR66S8H6aGmLghREqh3 slug _profile_...
2023-06-19 08:32:22.405008-0700 Subconscious[1751:47338466] [DataService] msg="Indexed memo /_profile_" slashlink="/_profile_"
Reading sphere did:key:z6Mko6McViVcsDSBkaZmn39tvqPQpvR66S8H6aGmLghREqh3 slug baby-dont-hurt-me...
2023-06-19 08:32:22.408707-0700 Subconscious[1751:47338466] [DataService] msg="Indexed memo /baby-dont-hurt-me" slashlink="/baby-dont-hurt-me"
Reading sphere did:key:z6Mko6McViVcsDSBkaZmn39tvqPQpvR66S8H6aGmLghREqh3 slug dont-hurt-me...
2023-06-19 08:32:22.410267-0700 Subconscious[1751:47338466] [DataService] msg="Indexed memo /dont-hurt-me" slashlink="/dont-hurt-me"
Reading sphere did:key:z6Mko6McViVcsDSBkaZmn39tvqPQpvR66S8H6aGmLghREqh3 slug gizmo...
2023-06-19 08:32:22.411642-0700 Subconscious[1751:47338466] [DataService] msg="Indexed memo /gizmo" slashlink="/gizmo"
Reading sphere did:key:z6Mko6McViVcsDSBkaZmn39tvqPQpvR66S8H6aGmLghREqh3 slug hi-gordon...
2023-06-19 08:32:22.413015-0700 Subconscious[1751:47338466] [DataService] msg="Indexed memo /hi-gordon" slashlink="/hi-gordon"
Reading sphere did:key:z6Mko6McViVcsDSBkaZmn39tvqPQpvR66S8H6aGmLghREqh3 slug hi-to-ben...
2023-06-19 08:32:22.417057-0700 Subconscious[1751:47338466] [DataService] msg="Indexed memo /hi-to-ben" slashlink="/hi-to-ben"
Reading sphere did:key:z6Mko6McViVcsDSBkaZmn39tvqPQpvR66S8H6aGmLghREqh3 slug interesting-ideas-from-the-noosphere...
2023-06-19 08:32:22.420631-0700 Subconscious[1751:47338466] [DataService] msg="Indexed memo /interesting-ideas-from-the-noosphere" slashlink="/interesting-ideas-from-the-noosphere"
Reading sphere did:key:z6Mko6McViVcsDSBkaZmn39tvqPQpvR66S8H6aGmLghREqh3 slug itali...
2023-06-19 08:32:22.422517-0700 Subconscious[1751:47338466] [DataService] msg="Indexed memo /itali" slashlink="/itali"
Reading sphere did:key:z6Mko6McViVcsDSBkaZmn39tvqPQpvR66S8H6aGmLghREqh3 slug no-more...
2023-06-19 08:32:22.423956-0700 Subconscious[1751:47338466] [DataService] msg="Indexed memo /no-more" slashlink="/no-more"
Reading sphere did:key:z6Mko6McViVcsDSBkaZmn39tvqPQpvR66S8H6aGmLghREqh3 slug this-is-a-triumph...
2023-06-19 08:32:22.425415-0700 Subconscious[1751:47338466] [DataService] msg="Indexed memo /this-is-a-triumph" slashlink="/this-is-a-triumph"
Reading sphere did:key:z6Mko6McViVcsDSBkaZmn39tvqPQpvR66S8H6aGmLghREqh3 slug trustnet...
2023-06-19 08:32:22.428547-0700 Subconscious[1751:47338466] [DataService] msg="Indexed memo /trustnet" slashlink="/trustnet"
Reading sphere did:key:z6Mko6McViVcsDSBkaZmn39tvqPQpvR66S8H6aGmLghREqh3 slug what-is-love...
2023-06-19 08:32:22.430497-0700 Subconscious[1751:47338466] [DataService] msg="Indexed memo /what-is-love" slashlink="/what-is-love"
2023-06-19 08:32:22.431835-0700 Subconscious[1751:47338466] [DataService] msg="Indexed peer" petname="cdata" identity="did:key:z6Mko6McViVcsDSBkaZmn39tvqPQpvR66S8H6aGmLghREqh3" version="bafyr4ifyqruqswigidlxxxma25o4nv4jc2depin4padtqvej6intmetxbi" since="nil"
2023-06-19 08:32:22.432909-0700 Subconscious[1751:47338466] [Sphere] deinit with identity did:key:z6Mko6McViVcsDSBkaZmn39tvqPQpvR66S8H6aGmLghREqh3
2023-06-19 08:32:22.433433-0700 Subconscious[1751:47338039] [app] [action] succeedIndexPeer(Subconscious.PeerRecord(petname: cdata, identity: did:key:z6Mko6McViVcsDSBkaZmn39tvqPQpvR66S8H6aGmLghREqh3, since: Optional("bafyr4ifyqruqswigidlxxxma25o4nv4jc2depin4padtqvej6intmetxbi")))
2023-06-19 08:32:22.433650-0700 Subconscious[1751:47338039] [app] msg="Indexed peer" petname="cdata" identity="did:key:z6Mko6McViVcsDSBkaZmn39tvqPQpvR66S8H6aGmLghREqh3" since="bafyr4ifyqruqswigidlxxxma25o4nv4jc2depin4padtqvej6intmetxbi"
2023-06-19 08:32:25.428367-0700 Subconscious[1751:47338039] [app] [action] setAppUpgraded(true)
Reading sphere did:key:z6MkqWcTm7VxZbRAWEvBY8MajNaoVw8uuWfuS2hpjo4H9k6w slug _profile_...
2023-06-19 08:32:28.116297-0700 Subconscious[1751:47338039] [notebook] [action] requestOurProfileDetail
2023-06-19 08:32:28.125467-0700 Subconscious[1751:47338039] [notebook] [action] pushOurProfileDetail(Subconscious.UserProfile(did: did:key:z6MkqWcTm7VxZbRAWEvBY8MajNaoVw8uuWfuS2hpjo4H9k6w, nickname: Optional(cdata-sim), address: /_profile_, pfp: Subconscious.ProfilePicVariant.none(did:key:z6MkqWcTm7VxZbRAWEvBY8MajNaoVw8uuWfuS2hpjo4H9k6w), bio: Subconscious.UserProfileBio(text: "”I\'ve got a lovely bunch of coconuts; there they are, all standing in a row Big ones, small ones, some as big as your head; give them a twist a flick of the wrist; that\'s what the showman said” ~ Zazu"), category: Subconscious.UserCategory.you, resolutionStatus: Subconscious.ResolutionStatus.resolved("bafyr4idhnx4deslhqtoxcqns7vzx5obdgshwbzisbcu2o4e5r2aksqbkvu"), ourFollowStatus: Subconscious.UserProfileFollowStatus.notFollowing))
2023-06-19 08:32:28.189302-0700 Subconscious[1751:47338039] [UserProfileDetailView] [action] appear(/_profile_, 2, Optional(Subconscious.UserProfile(did: did:key:z6MkqWcTm7VxZbRAWEvBY8MajNaoVw8uuWfuS2hpjo4H9k6w, nickname: Optional(cdata-sim), address: /_profile_, pfp: Subconscious.ProfilePicVariant.none(did:key:z6MkqWcTm7VxZbRAWEvBY8MajNaoVw8uuWfuS2hpjo4H9k6w), bio: Subconscious.UserProfileBio(text: "”I\'ve got a lovely bunch of coconuts; there they are, all standing in a row Big ones, small ones, some as big as your head; give them a twist a flick of the wrist; that\'s what the showman said” ~ Zazu"), category: Subconscious.UserCategory.you, resolutionStatus: Subconscious.ResolutionStatus.resolved("bafyr4idhnx4deslhqtoxcqns7vzx5obdgshwbzisbcu2o4e5r2aksqbkvu"), ourFollowStatus: Subconscious.UserProfileFollowStatus.notFollowing)))
Reading sphere did:key:z6MkrdX8pUfnGef3zwzDo5etdiz57pvdT9T2bmiM4UGwVPka slug _profile_...
Reading sphere did:key:z6Mko6McViVcsDSBkaZmn39tvqPQpvR66S8H6aGmLghREqh3 slug _profile_...
Reading sphere did:key:z6MktdGJAekLdBE7X7t4wUv9tAqVeq1pYuNzDYHkEWtbiMKj slug _profile_...
Reading sphere did:key:z6MkoKiwk5zzNn8Ugo3BeXqa5mapC6S8aJdd953WY4ArVHe6 slug _profile_...
2023-06-19 08:32:28.190666-0700 Subconscious[1751:47338464] [UserProfileService] Failed to read profile at @subconscious/_profile_: Foreign Error: No version has been resolved for "subconscious" (did:key:z6MkmCJAZansQ3p1Qwx6wrF4c64yt2rcM8wMrH5Rh7DGb2K7)
Reading sphere did:key:z6MkqWcTm7VxZbRAWEvBY8MajNaoVw8uuWfuS2hpjo4H9k6w slug some-thoughts...
Reading sphere did:key:z6MkqWcTm7VxZbRAWEvBY8MajNaoVw8uuWfuS2hpjo4H9k6w slug who-am-ai...
Reading sphere did:key:z6MkqWcTm7VxZbRAWEvBY8MajNaoVw8uuWfuS2hpjo4H9k6w slug _profile_...
2023-06-19 08:32:28.273704-0700 Subconscious[1751:47338039] [UserProfileDetailView] [action] populate(...)
2023-06-19 08:32:31.953164-0700 Subconscious[1751:47338039] [notebook] [action] setDetails([])
```

**Comment by gordonbrander** [comment] 2023-06-22 15:27
Yup, dupe of #723.

Per https://github.com/subconsciousnetwork/subconscious/issues/723#issuecomment-1595169756, I suspect this may be caused by the following: 

> Wild guess without any info: these were sphere notes, and when https://github.com/subconsciousnetwork/subconscious/pull/627 was flashed, Noosphere was off. Thus, the gateway sync was not kicked off, and after it, the sphere sync was not kicked off. Since there were no local drafts, the app showed an empty state.

If so, this is more of an artifact of the upgrade than a bug, I think?

**Closed by gordonbrander** 2023-06-22 15:27 UTC
